version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - mynetwork
    ports:
      - 5672:5672
      - 15672:15672

  elasticsearch:
    image: elasticsearch:7.12.1
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - mynetwork

  elasticsearch_hq:
    image: elastichq/elasticsearch-hq
    container_name: elasticsearch_hq
    depends_on:
      - elasticsearch
    environment:
      - "HQ_DEFAULT_URL=http://elasticsearch:9200"
    ports:
      - 5050:5000
    networks:
      - mynetwork

  productservice:
    image: simplecqrsmicroservice/productservice:1.0
    build:
      context: src/
      dockerfile: ProductService/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - mynetwork
    ports:
      - 5102:80


  productsearchservice:
    image: simplecqrsmicroservice/productsearchservice:1.0
    build:
      context: src/
      dockerfile: ProductSearchService/Dockerfile
    depends_on:
      - rabbitmq
      - productservice
      - elasticsearch
    networks:
      - mynetwork
    ports:
      - 5101:80

volumes:
  data01:
    driver: local
 
networks:
  mynetwork: 
    driver: bridge